# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B7Gio5z3ysBuTs-a0Rmx-IAUHB_0T_Py
"""

import numpy as np
dir(np)

import numpy as np
a=np.array([1,2,3,4])

type(a)

a

a1=np.array([[1,2],[2,3],[3,4]])
type(a1)

a1

a1.shape

a1[0][1]

x=np.full((2,2),4)
y=np.full((2,2),5)

x+2

x+y

